In [1]:
from sync_workbench.storage.sqlite_store import SQLiteCoreStore

sqlite_path = "workbench.sqlite"

store = SQLiteCoreStore(sqlite_path)

In [4]:
df_mv = store.read_table("MAPPING_VERSION")

In [ ]:
df_mv.iloc[0]['mapping_version_id'].value

In [5]:
df_mv

,subject_id,mapping_version_id,source_run_id,source_device_type,target_run_id,target_device_type,mapping_name,mapping_method,created_at,parent_mapping_version_id,source_sync_model_id,parameters_json,notes
0,07_SW,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,Session-2023-November-27 14-11-02-690792,kinect_rgb,Session-2023-November-27 13-59-35-723243,radar_pc,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,initial_nearest_for_anchoring,2026-07-05T03:28:59.509819,,sync_identity_Session-2023-November-27_14-11-0...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
1,07_SW,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,Session-2023-November-27 14-25-15-245640,kinect_rgb,Session-2023-November-27 14-25-09-526763,radar_pc,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,initial_nearest_for_anchoring,2026-07-05T03:29:42.080679,,sync_identity_Session-2023-November-27_14-25-1...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
2,07_SW,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,Session-2023-November-27 14-25-15-245640,kinect_rgb,Session-2023-November-27 14-44-35-753073,radar_pc,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,initial_nearest_for_anchoring,2026-07-05T03:29:54.734134,,sync_identity_Session-2023-November-27_14-25-1...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
3,07_SW,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,Session-2023-November-27 14-57-05-570695,kinect_rgb,Session-2023-November-27 14-56-26-249587,radar_pc,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,initial_nearest_for_anchoring,2026-07-05T03:30:38.946191,,sync_identity_Session-2023-November-27_14-57-0...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
4,07_SW,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,Session-2023-November-27 14-57-05-570695,kinect_rgb,Session-2023-November-27 15-15-17-817205,radar_pc,initial_rgb_to_pc_v001__07_SW__Session-2023-No...,initial_nearest_for_anchoring,2026-07-05T03:30:51.196776,,sync_identity_Session-2023-November-27_14-57-0...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
5,19_MM,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,initial_nearest_for_anchoring,2026-07-05T03:31:13.971728,,sync_identity_Session-2024-January-15_09-47-41...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
6,19_MM,piecewise_rgb_to_pc_v001_map,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,piecewise_rgb_to_pc_v001_map,nearest_predicted_time,2026-07-17T05:52:36.548181,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,piecewise_rgb_to_pc_v001,"{""extrapolation_policy"": ""disallow"", ""max_allo...",Mapping generated from a piecewise_affine sync...

In [10]:
df_dr = store.read_table("DEVICE_RUN")
df_sm = store.read_table("SAMPLE_MAPPING")
df_ste = store.read_table("SAMPLE_TIME_ESTIMATE")
df_mv = store.read_table("MAPPING_VERSION")
df_rtm = store.read_table("RUN_TIMELINE_MODEL")
df_sm = store.read_table("SYNC_MODEL")

In [11]:
df_sm

,subject_id,sync_model_id,source_run_id,source_device_type,target_run_id,target_device_type,source_timeline_model_id,target_timeline_model_id,model_name,model_type,extrapolation_policy,parameters_json,notes
0,07_SW,sync_identity_Session-2023-November-27_14-11-0...,Session-2023-November-27 14-11-02-690792,kinect_rgb,Session-2023-November-27 13-59-35-723243,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
1,07_SW,sync_identity_Session-2023-November-27_14-25-1...,Session-2023-November-27 14-25-15-245640,kinect_rgb,Session-2023-November-27 14-25-09-526763,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
2,07_SW,sync_identity_Session-2023-November-27_14-25-1...,Session-2023-November-27 14-25-15-245640,kinect_rgb,Session-2023-November-27 14-44-35-753073,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
3,07_SW,sync_identity_Session-2023-November-27_14-57-0...,Session-2023-November-27 14-57-05-570695,kinect_rgb,Session-2023-November-27 14-56-26-249587,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
4,07_SW,sync_identity_Session-2023-November-27_14-57-0...,Session-2023-November-27 14-57-05-570695,kinect_rgb,Session-2023-November-27 15-15-17-817205,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
5,19_MM,sync_identity_Session-2024-January-15_09-47-41...,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,Identity-time mapping between selected timelines,identity_time,disallow,"{""coordinate_kind"": ""datetime_or_numeric_check...",v0.1 trivial sync model used for nearest-time ...
6,19_MM,piecewise_rgb_to_pc_v001,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,rgb_wallclock_from_pts,radar_pc_linear_from_index,piecewise_rgb_to_pc_v001,piecewise_affine,disallow,"{""anchor_pairs"": [{""anchor_id"": ""anchor_19_MM_...",Piecewise affine sync model fitted from canoni...

In [20]:
#sync_identity_Session-2024-January-15_09-47-41-274452_kinect_rgb_rgb_wallclock_from_pts__Session-2024-January-15_09-43-27-126274_radar_pc_radar_pc_linear_from_index
df_mv[df_mv['subject_id']=="19_MM"]

,subject_id,mapping_version_id,source_run_id,source_device_type,target_run_id,target_device_type,mapping_name,mapping_method,created_at,parent_mapping_version_id,source_sync_model_id,parameters_json,notes
5,19_MM,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,initial_nearest_for_anchoring,2026-07-05T03:31:13.971728,,sync_identity_Session-2024-January-15_09-47-41...,"{""allow_numeric_identity"": false, ""extrapolati...",Crude nearest-time mapping generated to help a...
6,19_MM,piecewise_rgb_to_pc_v001_map,Session-2024-January-15 09-47-41-274452,kinect_rgb,Session-2024-January-15 09-43-27-126274,radar_pc,piecewise_rgb_to_pc_v001_map,nearest_predicted_time,2026-07-17T05:52:36.548181,initial_rgb_to_pc_v001__19_MM__Session-2024-Ja...,piecewise_rgb_to_pc_v001,"{""extrapolation_policy"": ""disallow"", ""max_allo...",Mapping generated from a piecewise_affine sync...

In [29]:
list(df_mv[df_mv['subject_id']=='19_MM']['mapping_version_id'].to_numpy())

['initial_rgb_to_pc_v001__19_MM__Session-2024-January-15_09-47-41-274452__Session-2024-January-15_09-43-27-126274']

In [25]:
df_dr[df_dr['subject_id']=='19_MM']

,subject_id,run_id,device_type,start_wallclock_est,end_wallclock_est,nominal_fps,notes
27,19_MM,Session-2024-January-15 09-47-41-274452,kinect_rgb,2024-01-15T09:48:05.445703,2024-01-15T10:36:00.777000,15,
42,19_MM,Session-2024-January-15 09-43-27-126274,radar_pc,2024-01-15T09:44:08.352672,2024-01-15T10:35:37.858891,20,
82,19_MM,Session-2024-January-15 09-43-27-126274,radar_raw,2024-01-15T09:44:08.000000,2024-01-15T10:35:37.000000,20,
133,19_MM,Session-2024-January-15 09-44-58-635833,imu_accel,2024-01-15T09:45:19.143685,2024-01-15T09:54:37.280049,20,
134,19_MM,Session-2024-January-15 09-59-40-814417,imu_accel,2024-01-15T10:00:02.275163,2024-01-15T10:35:42.820544,20,

In [12]:
df_mv[df_mv['subject_id']=="07_SW"]['mapping_version_id'].iloc[0]

'initial_rgb_to_pc_v001__07_SW__Session-2023-November-27_14-11-02-690792__Session-2023-November-27_13-59-35-723243'

In [3]:
from sync_workbench.sync.mapping import TimelineSelection
subject = "19_MM" #"07_SW"
source_run = "Session-2024-January-15 09-47-41-274452"
target_run = "Session-2024-January-15 09-43-27-126274" #"Session-2023-November-27 13-59-35-723243"
source_device = "kinect_rgb"
target_device = "radar_pc"
source_timeline = "rgb_wallclock_from_pts"
target_timeline = "radar_pc_linear_from_index"

source_selection = TimelineSelection(subject, source_run, source_device, source_timeline)
target_selection = TimelineSelection(subject, target_run, target_device, target_timeline)

rgb_mask = (
    (df_ste["subject_id"] == source_selection.subject_id)
    & (df_ste["run_id"] == source_selection.run_id)
    & (df_ste["device_type"] == source_selection.device_type)
    & (df_ste["timeline_model_id"] == source_selection.timeline_model_id)
)
pc_mask = (
    (df_ste["subject_id"] == target_selection.subject_id)
    & (df_ste["run_id"] == target_selection.run_id)
    & (df_ste["device_type"] == target_selection.device_type)
    & (df_ste["timeline_model_id"] == target_selection.timeline_model_id)
)

rg_ste = df_ste.loc[rgb_mask]
pc_ste = df_ste.loc[pc_mask]

In [4]:
print(rg_ste[['time_value_sec','time_value_datetime','reference_time_datetime']].iloc[0])
print(pc_ste[['time_value_sec','time_value_datetime','reference_time_datetime']].iloc[0])

time_value_sec                                    NaN
time_value_datetime        2024-01-15T09:48:05.445703
reference_time_datetime    2024-01-15T09:48:05.445703
Name: 263864, dtype: object
time_value_sec                                    NaN
time_value_datetime        2024-01-15T09:44:08.296777
reference_time_datetime    2024-01-15T09:44:08.352672
Name: 641137, dtype: object

In [24]:
pc_ste.columns

Index(['subject_id', 'run_id', 'device_type', 'timeline_model_id',
       'sample_index', 'time_value_datetime', 'time_value_sec', 'time_kind',
       'reference_time_datetime', 'residual_ms', 'notes'],
      dtype='str')

In [ ]:
from sync_workbench.core.time_utils import datetime_to_epoch_seconds, utc_now_str

dt_text = rg_ste["time_value_datetime"].fillna("").astype(str).str.strip()
has_datetime = dt_text.ne("") & ~dt_text.str.lower().isin({"nan", "none", "nat"})
rg_ste["time_value_datetime"].map(datetime_to_epoch_seconds).iloc[0]
#first rgb frame seconds: 1705312085.445703

dt_text = pc_ste["time_value_datetime"].fillna("").astype(str).str.strip()
pc_ste["time_value_datetime"].map(datetime_to_epoch_seconds).iloc[0]
#first pc frame seconds: 1705351448.296777

np.float64(1705351448.296777)

In [14]:
#all is_primary==0
#
min_delta_idx = df_sm['predicted_minus_estimated_ms'].argmin()
df_sm.iloc[min_delta_idx]

subject_id                                                        19_MM
mapping_version_id                               rgb_to_pc_initial_v001
source_run_id                   Session-2024-January-15 09-47-41-274452
source_device_type                                           kinect_rgb
source_sample_index                                               34285
target_run_id                   Session-2024-January-15 09-43-27-126274
target_device_type                                             radar_pc
target_sample_index                                                   0
predicted_minus_estimated_ms                         36490717.751026154
rank                                                                  1
is_primary                                                            0
mapping_region_type                                  left_extrapolation
support_status                                              outside_run
confidence_score                                                    0.0
Name: 102855, dtype: str

In [13]:
import pandas as pd
rpc_path_zst = "C:/Users/GSBME/SmartCupStudy/Unified_network/data_sets/UNSW-PANOPTES/UNSW-PANOPTES-ETL-Pipeline/docs/sync_workbench/temp_ingestion_package/radar_pc_samples.zst"
rpcs_df = pd.read_pickle(rpc_path_zst, compression="infer")

rgb_path_zst = "C:/Users/GSBME/SmartCupStudy/Unified_network/data_sets/UNSW-PANOPTES/UNSW-PANOPTES-ETL-Pipeline/docs/sync_workbench/temp_ingestion_package/rgb_samples.zst"
rgbs_df = pd.read_pickle(rgb_path_zst, compression="infer")

In [16]:
rgbs_df['video_ref'].iloc[0]

'07_SW/Session-2023-November-27 14-11-02-690792/kinect_camera_recording_rgb_lq.mp4'

In [25]:
rgbs_df['conf2d_shape'].unique()

array([(0,), (1,), (2,), (3,)], dtype=object)

In [7]:
rpcs_df['points_shape_len'] = rpcs_df['points'].apply(lambda x: len(x.shape))

In [9]:
rpcs_df['points_shape_len'].unique()

array([1])

In [1]:
import torch 

run = torch.load("runs\\mmfi_pose_quick\\best.pt", weights_only=False)

In [8]:
run.keys()

dict_keys(['model', 'model_config', 'pose_bounds', 'mmfi_point_order', 'mmfi_pose_order', 'coco17_names', 'epoch', 'val_metrics', 'window_size'])

>>> x = np.load("frame001.npy")
>>> x
array([[335.82537842, 132.25393677],
       [341.38049316, 124.97851562],
       [328.12335205, 126.07394409],
       [349.38110352, 130.34649658],
       [317.36126709, 132.47698975],
       [364.60467529, 173.95782471],
       [301.96063232, 172.83380127],
       [380.29138184, 223.71408081],
       [278.90673828, 218.11709595],
       [343.55950928, 203.61502075],
       [318.10797119, 200.91708374],
       [347.24255371, 281.53222656],
       [304.8772583 , 278.18789673],
       [339.72186279, 357.42721558],
       [292.7409668 , 347.14706421],
       [331.02825928, 430.20388794],
       [296.40515137, 414.28909302]])
>>> x.shape
(17, 2)